name: main
description: A simple example of how to use bsdiff to generate and apply patches.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.1.1-dev.2.0 <3.0.0"

dependencies:
  bsdiff:
    path: ..
